name: Verja

on: 
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  alert:
    runs-on: verja:latest
    steps:
    - uses: actions/checkout@master
    - uses: digitalist-se/verja@master
      env:
        ENV CONFIG:config.yml
        ENV CPE:cpe.txt
    - name: done
      run: echo 'done'
